trigger:
  - main

pool:
  vmImage: 'windows-2022'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'

  - task: AzureFunctionApp@1
    inputs:
      azureSubscription: 'VotreConnexionAzure'
      appType: 'functionApp'
      appName: 'NomDeVotreFunctionApp'
      package: '$(Build.ArtifactStagingDirectory)'
